#!/bin/sh

INPUT="$1"
OUTPUT="$2"
OPTION="${3}"

gimp-console --gegl-threads=$(getconf _NPROCESSORS_ONLN) -i --batch-interpreter=python-fu-eval -b - << EOF
import gimpfu

def convert(input, output, option=None):
    img = pdb.gimp_file_load(input, input)
    layer = pdb.gimp_image_merge_visible_layers(img, 1)
    if option and option == "rgb" and img.base_type != RGB:
        pdb.gimp_image_convert_rgb(img)

    pdb.gimp_file_save(img, layer, output, output)
    pdb.gimp_image_delete(img)

convert('${INPUT}', '${OUTPUT}', '${OPTION}')

pdb.gimp_quit(1)
EOF
