../gfxboot/background.png:
	../../gimp/xcf2png ../background/Moondrake-tux-1024x768.xcf Moondrake-tux-1024x768.png rgb
	pngcrush -ow Moondrake-tux-1024x768.png $@
	rm -f Moondrake-tux-1024x768.png

clean:
	rm -f background.png
